### PR TITLE
Adding dropdown filter for related AR in gridview

### PR DESCRIPTION
**Pull request by samuelm**
A simple modification that generate a dropdown filter for foreign key in grid view.

### CODE REVIEW

**Comment by isDipesh** [comment]
I have cherry picked the first commit. Thank you very much!

**Comment by samuelm** [comment]
Yes sure second one was just a merge of your last modifcations.
I fogot to update mine before commit the changes. 

I also have a version to be use with bootstrap extension http://www.cniska.net/yii-bootstrap/setup.html . 
What do you think about  adding options to enable/disable this compatibility feature on awegen ?

If you think it could be cool i'll pull it.

Thanks for your good works .

**Comment by isDipesh** [comment]
Actually, I was looking for it. Our front-end developer loves Bootstrap. Excited to see it in action.

**Comment by samuelm** [comment]
Ok, i'll review my codes , add some dosc/comments and i'll pull it as soon
as possible.

On Sat, Jun 30, 2012 at 10:47 AM, Dipesh Acharya <
reply@reply.github.com

**Pull request closed without merging**
